// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe5L_Ke3lmKxf3smPCCGaNxQfD18x4-wg',
    appId: '1:204173235803:web:7faa8db82e0b7ad259d17e',
    messagingSenderId: '204173235803',
    projectId: 'imtapps',
    authDomain: 'imtapps.firebaseapp.com',
    storageBucket: 'imtapps.firebasestorage.app',
    measurementId: 'G-FZPDXL5FJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWfm4t29bEoXgbm3FSszsPp9NpJz67ySs',
    appId: '1:204173235803:android:90b01422ce59b37459d17e',
    messagingSenderId: '204173235803',
    projectId: 'imtapps',
    storageBucket: 'imtapps.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz-C7LXw0xDIzgZHmtR7N0lPR04kVjiOY',
    appId: '1:204173235803:ios:02ebaa0a30b209aa59d17e',
    messagingSenderId: '204173235803',
    projectId: 'imtapps',
    storageBucket: 'imtapps.firebasestorage.app',
    iosBundleId: 'com.example.flutterTa2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz-C7LXw0xDIzgZHmtR7N0lPR04kVjiOY',
    appId: '1:204173235803:ios:02ebaa0a30b209aa59d17e',
    messagingSenderId: '204173235803',
    projectId: 'imtapps',
    storageBucket: 'imtapps.firebasestorage.app',
    iosBundleId: 'com.example.flutterTa2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe5L_Ke3lmKxf3smPCCGaNxQfD18x4-wg',
    appId: '1:204173235803:web:6de9e2ccf526d2d459d17e',
    messagingSenderId: '204173235803',
    projectId: 'imtapps',
    authDomain: 'imtapps.firebaseapp.com',
    storageBucket: 'imtapps.firebasestorage.app',
    measurementId: 'G-KL205MSC0X',
  );
}
